const socketio = require('socket.io');
const logger = require('./logger');

let io;

// Maps sessionId (generated by the client) → socket.id (assigned by socket.io)
const sessionSocketMap = new Map();

const socketConnection = (socket) => {
    logger.info('New socket connection', { socketId: socket.id });

    /**
     * Client sends its sessionId immediately after connecting so we can
     * route webhook payloads back to this specific browser tab.
     */
    socket.on('register_session', (sessionId) => {
        sessionSocketMap.set(sessionId, socket.id);
        logger.info('Session registered', { sessionId, socketId: socket.id });
    });

    socket.on('disconnect', () => {
        for (const [sessionId, socketId] of sessionSocketMap.entries()) {
            if (socketId === socket.id) {
                sessionSocketMap.delete(sessionId);
                logger.info('Session unregistered on disconnect', { sessionId, socketId: socket.id });
            }
        }
    });
};

/**
 * Push the identity-resolution result to the specific browser session.
 * @param {string} sessionId  - sessionId generated by the client at page load
 * @param {object} eventData  - payload forwarded to the client (html, linkedinUrl, resolutionLatency)
 * @returns {boolean} true if the push succeeded, false if the session is unknown
 */
const pushToSession = (sessionId, eventData) => {
    const socketId = sessionSocketMap.get(sessionId);
    if (!socketId) {
        logger.warn('No socket found for session', { sessionId });
        return false;
    }

    io.to(socketId).emit('identity_resolved', eventData);
    logger.info('Pushed identity result to session', { sessionId, socketId, eventData });
    return true;
};

const startIo = (server) => {
    io = socketio(server, {
        cors: { origin: '*' },
    });

    io.on('connection', socketConnection);
    logger.info('Socket.io initialized');
    return io;
};

module.exports = { startIo, pushToSession };
